### PR TITLE
[WIP] Adding TaskCluster CLI to the tutorial

### PR DESCRIPTION
**Pull request by t0xicCode**
This is regarding taskcluster/taskcluster-cli#62.

### CODE REVIEW

**Comment by djmitche** [comment]
(I'm using this to test taskcluster-github, sorry for the noise)

**Comment by djmitche** [comment]
@t0xicCode this is looking good - and a great idea!

**Comment by djmitche** [comment]
@t0xicCode any chance you want to finish this up?

**Comment by t0xicCode** [comment]
Yes! I'll finish it up and push it up

**Pull request closed without merging**
