### PR TITLE
point at s3 for gecko docs; rtd appears to be busted

### PR DESCRIPTION
**Pull request by escapewindow**

### CODE REVIEW

**Comment by djmitche** [comment]
@escapewindow can you redraft to use https://firefox-source-docs.mozilla.org?

**Comment by escapewindow** [comment]
@djmitche done. currently throwing ssl cert errors, but http:// works, and i imagine we're issuing a cert soon.

**Comment by djmitche** [comment]
Looks good.  I'll merge once the TLS certificate is set up.

**Comment by djmitche** [comment]
It's deploying now..

**Pull request merged**
