### PR TITLE
Interactive tutorial

### PR DESCRIPTION
**Pull request by EggyLv999**
As it currently stands, I can't get the https request to request properly from the queue for the socket artifact. It works in node but not here in browserify. If it ends up not working, you can just kill the lines from 106 and on to make a half-tutorial.

### CODE REVIEW

**Comment by EggyLv999** [comment]
Also the workerType needs to be changed when we deploy interactive to all amis

**Comment by jonasfj** [comment]
Well, we'll just have to play with it... I suspect this might even be a queue issue... As it doesn't look like it redirects when `Connection: Upgrade` is provided... And I'm not sure WebSockets can be redirected.

So that'll need testing and if not, we'll just create a JSON artifact with the websocket URL.

Anyways, thanks for your work!

**Comment by petemoore** [comment]
@jonasfj I'm worried this might bit rot. Should we create a bug against the Queue if it is likely to be a Queue issue?

**Comment by EggyLv999** [comment]
It is not a Queue issue. If I remember correctly, the browser will force you to take redirects, which is in conflict with the way that we currently use redirect artifacts. I don't think there's much that can be done to fix this issue without rewriting the entire process by which interactive artifacts are passed into the queue, which is probably not worth it.

**Comment by jonasfj** [comment]
Well, nothing uses the redirect artifact, so we should probably just replace it with a json file containing the information...
If we can't sort out the redirect which I fear is hard... Hmm... Haven't check if we can though...

**Comment by djmitche** [comment]
@jonasfj what do you want to do with this PR?  The reorganization will further bitrot this, but it would be great to include (although I don't see programmatic use of the interactive feature as a particularly common use-case)

**Comment by jonasfj** [comment]
Moving this in wouldn't cause much problems... even with the switch, most of this is text and examples..

I wish we could land it... but it's my understanding that it doesn't work... We removed the `interactive.sock` artifact after we discovered that it wouldn't work because we can't do GET requests without following redirects in the browser.

I think we might change it into a `sock.json` artifact or something... So there is no redirect involved.
But this haven't happened yet, so we can fix this tutorial...

Hence, I propose we just leave this PR for now, and pick it up on a rainy day.

**Pull request closed without merging**
