### PR TITLE
Bug 1252948: doc the new repo..cron roles

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by jonasfj** [comment]
Can't perhaps @jhford has a better name than "cron"... I'm thinking anything more generic..
@jhford I'm referencing you because you once said "I'm good at naming stuff" hehe ;)

**Comment by jhford** [comment]
"recurring-task"

**Comment by djmitche** [comment]
Is that just for the scope pattern?  Everything in the in-tree configs is named "cron" and I think it makes good sense there.

**Comment by jonasfj** [comment]
okay, I guess if in-tree configs say cron, then that works in the
scope-pattern.

--
Regards Jonas Finnemann Jensen.

2017-01-05 17:59 GMT+01:00 Dustin J. Mitchell <notifications@github.com>:

**Pull request merged**
