### PR TITLE
use cors-proxy for github readme

### PR DESCRIPTION
**Pull request by kristelteng**
Cors-proxy is being added to the data-doc-readme processor. It now uses cors-proxy.

### CODE REVIEW

**Comment by djmitche** [comment]
This looks good!  However, I expect it would need the whitelist updated on cors-proxy first:

  https://github.com/taskcluster/cors-proxy/blob/master/server.js#L12

does it work without that?

**Comment by kristelteng** [comment]
djmitche: Yes it was added and recently merged by Wander.

**Comment by djmitche** [comment]
Awesome :)

**Comment by kristelteng** [comment]
djmitche: Wander merged it and he will deploy on heroku on monday :)

**Pull request merged**
