### PR TITLE
Remove the scheduler since it's not a thing anymore and hasn't been for a long time

### PR DESCRIPTION
**Pull request by imbstack**
Not sure we actually want to land this, but it removes one more thing from the build that isn't through lib-docs. It also cleans up the references section somewhat.

Inspired by https://bugzilla.mozilla.org/show_bug.cgi?id=1290300

### CODE REVIEW

**Comment by jonasfj** [comment]
@imbstack, this is a different scheduler... No idea if it's still used... I
wouldn't be surprised... We should ask jlund.

Den 27. feb. 2017 1.48 PM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by imbstack** [comment]
Augh, ok. Heroku seems to think the other scheduler still gets some traffic.

**Comment by djmitche** [comment]
This is definitely still in use - the question is, is it cool to undocument something we're still running?  I'm not sure the answer is "no"

**Comment by jonasfj** [comment]
wouldn't oppose removing it...

--
Regards Jonas Finnemann Jensen.

2017-02-27 20:14 GMT-08:00 Dustin J. Mitchell <notifications@github.com>:

**Comment by djmitche** [comment]
Let's remove it.  Current users know how it works, and we're not planning on changing that in any way other than shutting off the service.

**Pull request merged**
