### PR TITLE
Updating docs to use clean theme

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by eliperelman** [comment]
OK, I think this is ready for review. Ping me if you have any questions.

**Comment by imbstack** [comment]
Running this locally I've noticed these nits/issues:

* `yarn download` fails because it can't find gulp. `npm run download` still works just fine.
* The menu on the reference page is wonky at the moment. For instance, this 'api-docs' page is sitting there beneath the 'index' section but it doesn't appear to be related.
image

Otherwise looks pretty good to me.

**Comment by djmitche** [comment]
First off, I think this looks great!

But there are some issues.

First off, the text is about 45% larger now:

much-bigger

as someone who does not measure his high-dpi screen in acres, this bugs me, as it means I have to scroll just to read more than one paragraph at a time.  And I can't sit back far enough from my laptop to need a font that large, because my arms are only so long.

**Comment by djmitche** [comment]
It looks like page titles no longer appear?  For example, on https://docs.taskcluster.net/tutorial/debug-task, the "Debugging a Task" header is gone.

**Comment by eliperelman** [comment]
@imbstack can you remove your node_modules and try `yarn` again? It works fine for me locally, and I have removed and re-added my dependencies and it still works.

Looks like the menu nesting needs some more work, and I'll fix that. Good catch.

@djmitche I'll try dropping the font-size to 16px.

Also, I see the headers just fine, is there a JS error in your console or anything that might indicate a problem?

ss

**Comment by imbstack** [comment]
Ah, my version of yarn had a bug. Updated it and `yarn download` works great now!

**Comment by djmitche** [comment]
No, nothing in the console, but definitely no "Debugging a Task" .. weird!

**Comment by djmitche** [comment]
The 'active' TOC entry seems to be pulled left, too, making it look like a category for its peers.

**Comment by eliperelman** [comment]
@djmitche so, I have a CSS rule in there that hides all but the first `h1` so there wouldn't be duplicate headings from specifying `title` in the yaml front-matter. Can you tell me if you see the `h1` in the markup, but just not visible?

**Comment by eliperelman** [comment]
OK, PR updated with smaller font-size and more nesting on the sidebar.

**Comment by djmitche** [comment]
I don't see any h1 in the DOM:

screenshot from 2016-11-22 22-26-16

**Comment by eliperelman** [comment]
@djmitche can you explain your build process to me? Right now I have two tabs, one for `develop` script and one for `start` and I can't replicate this. Since the `h1` is missing from the DOM, something in the build process isn't working, so I'm trying to find that cause.

**Comment by eliperelman** [comment]
@djmitche can you also share the contents of your `layout/layout.pug` file?

**Comment by djmitche** [comment]
I'm re-merging against master, blowing away `node_modules`, and generally starting from scratch.  Will report back shortly.

**Comment by eliperelman** [comment]
whew!

**Pull request merged**
